### ISSUE TITLE
react-dom/server renderToNodeStream instrumentation

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#11]
See https://zeit.co/blog/streaming-server-rendering-at-spectrum

In general node streams are an interesting problem.  Do we want to generate an event for every `on('data')` callback?  what about the push/source side of things?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
