### ISSUE TITLE
Lambda Promise Example/Support

### ISSUE THREAD

**Issue by martin308** [honeycombio/beeline-nodejs#132]
It would be good to be able to support, have an example and document how to use the beeline in the scenario of using promises/async in a lambda

https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

**Comment by Zertz** [comment]
If it can be of any help, here's a simplified version of what we use with Vercel (which runs on AWS Lambda):

```js
const honeycomb = require("honeycomb-beeline")({
  writeKey: process.env.HONEYCOMB_WRITE_KEY,
  dataset: process.env.NODE_ENV,
});

function withTrace(fn) {
  return (req, res) => {
    const trace = honeycomb.startTrace({
      url: req.url,
    });

    req.trace = trace;

    return fn(req, res);
  };
}

module.exports = withTrace(async (req, res) => {
  try {
    honeycomb.customContext.add("something", req.query.something);
  } catch (e) {
    console.error(e);
  } finally {
    honeycomb.finishTrace(req.trace);

    await honeycomb.flush();

    red.end();
  }
});
```

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
