### ISSUE TITLE
Parse Root= from X-Amzn-Trace-Id when ALB header is used

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-nodejs#141]
I think all of X-Amzn-Trace-Id is used for `trace.trace_id` which is a bit much

**Comment by camerondunn-ns8** [comment]
@nathanleclaire Is this in reference to the parsing of a downstream 'X-Amzn-Trace-Id' header only capturing "Root" from an original ALB header?

For example, I have a situation where calls flow as:
ALB -> Service1 -> Service2. Both Service1 & Service2 are using beeline-nodejs

The behavior I see is:
1) ALB sets headers like: "X-Amzn-Trace-Id: Root=<someID>"
2) Service1's beeline parses "X-Amzn-Trace-Id" since no other trace header is present. Sets the 'trace_id' context to be "Root=<someID>".
3) When an outbound call from Service1 is made, the "X-Honeycomb-Trace" header is set to something like "1;trace_id=Root=<someID>,parent_id=<AnotherID>,dataset=<OutDataset?,context=<Base64Stuff>="
4) Service2 parses "X-Honeycomb-Trace" by splitting on "=" and reads the "trace_id" as "Root", not "Root=<someID>".

In the Honeycomb UI I can see a trace page where ALL requests to Service2 are considered part of one trace. I changed our traceID definition for our dataset to something else because I was afraid this wouldn't scale and would break the UI.

Is that the issue you're referring to? Is there a plan to fix this, or would you accept a pull request?

**Comment by nathanleclaire** [comment]
Haven't had a chance to review your comment in detail but we definitely welcome PRs!

**Comment by camerondunn-ns8** [comment]
@nathanleclaire PR can be found [here](https://github.com/honeycombio/beeline-nodejs/pull/182).

**Comment by paulosman** [comment]
This should be fixed in #187
