### ISSUE TITLE
Not clear how to easily add global metadata when configuring the beeline

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-nodejs#151]
The beeline-go package provides a way to configure global metadata/context that appears on every event or span created by the package. We use this to inject a bunch of "global" node-level metadata into all events, e.g.:

```json
{
  "aws.az": "us-east-1e",
  "aws.instance_type": "m3.large",
  "aws.ami_id": "ami-0c5942ba8297a25cd",
  "aws.eth0.subnet_id": "subnet-20c7a91c",
  "aws.eth0.public_ipv4": "3.90.65.134",
  "aws.eth0.private_ipv4": "10.0.0.159",
  "aws.eth0.security_groups": "kitchen-psi3s59t"
}
```

Unfortunately I can't see a way to pass this metadata to the beeline. The instance of libhoney this library uses is hidden in a private `apiImpl` variable in `api/index.js`, and this API does not expose methods for changing the default builder.

Ideally there'd be a way to pass this metadata through to the builder in the configuration, or a way to call `add()` on the underlying implementation. I realise there's a [`_apiForTesting`](https://github.com/honeycombio/beeline-nodejs/blob/c55f99ff8dbe99bcd45cea19b123b33a3490a757/lib/api/index.js#L140-L142) function, but the name seems to suggest it shouldn't be used!

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
