### ISSUE TITLE
mongo instrumentation breaks interface for v2.2 mongo drivers

### ISSUE THREAD

**Issue by chris-armstrong** [honeycombio/beeline-nodejs#165]
I'm using honeycomb-beeline in an application that has a mongodb driver. I'm using an old version of the mongodb driver (2.2 series) but I think the instrumentation assumes v3.x.

In my case, my application is broken by including honeycomb-beeline by the assumptions it makes about the mongodb interface. My callbacks are not invoked because the arguments to mongodb.collection.createIndexes() are being changed such that an `options` argument is being inserted, which doesn't exist for mongodb.collection.createIndexes() in version 2 (but does exist in version 3).

See the attached api documentation for more details:
**v2.2**: https://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#createIndexes
**v3.3**: https://mongodb.github.io/node-mongodb-native/3.3/api/Collection.html#createIndexes

At the very least, the instrumentation could make less assumptions about the methods being invoked and pass the same arguments instead of inserting a fake `options` parameter if it isn't provided.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
