### ISSUE TITLE
Inclusion into Node GraphQL app "brought down prod"

### ISSUE THREAD

**Issue by christineyen** [honeycombio/beeline-nodejs#169]
from https://twitter.com/RozenMD/status/1184650333672206336
> my setup is more or less this repo: https://github.com/rozenmd/graphql-resolvers
> talking to RDS hosted postgres via the pg-promise library
> 
> I'm guessing it's probably an issue with Babel more than anything else

Hoping to get more details. @rozenmd, would you share more about what "brought down prod" looked like?

**Comment by allyjweir** [comment]
Could this be related to this earlier issue raised regarding the `pg` instrumentation? https://github.com/honeycombio/beeline-nodejs/issues/164

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
