### ISSUE TITLE
Including beeline increases response time significantly

### ISSUE THREAD

**Issue by giuliano-barberi-tf** [honeycombio/beeline-nodejs#202]
On some of our endpoints which return a lot of data, it seems enabling beeline increases our response time by up to 30%. I've even gone as far as never creating an actual trace and it still seems to impact response time. I haven't been able to create a repro project and I'm not sure if it's specific circumstances which impact response time. I'm wondering if it would be possible to create an official benchmark for this project in order to make sure it's not impacting clients and whether anyone has seen what the overhead of this library is.

**Comment by andrewoh531** [comment]
I'm seeing response times increase for an endpoint that I've started instrumenting with more spans. 

Was there any configuration or modifications you made after seeing the increase in response times @giuliano-barberi-tf ?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
