### ISSUE TITLE
custom contexts can get multiple "app" prefixes

### ISSUE THREAD

**Issue by numso** [honeycombio/beeline-nodejs#207]
Let's imagine I have 3 services using express that depend on each other: A -> B -> C
Within A I call `beeline.addTraceContext({ foo: 'bar' })`. This custom trace context is then propagated to B and then C.

#### Expected
All of my spans have `app.foo: bar`

#### Actual
The span for A contains `app.foo: bar`.
The span for B contains `app.app.foo: bar`.
The span for C contains `app.app.app.foo: bar`.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
