### ISSUE TITLE
Ability to set application-wide context

### ISSUE THREAD

**Issue by numso** [honeycombio/beeline-nodejs#208]
I'd like to set a `region` and `environment` key on every span that leaves my app. This data doesn't change from request to request so I'd like to set it once. I'm able to accomplish this today but I have to use _apiForTesting which is not ideal:
```
require('honeycomb-beeline')(MY_CONFIG)._apiForTesting().honey.add({ region, environment })
```

It would be awesome to expose an API that did that:
```
require('honeycomb-beeline').addRootContext({ region, environment }) // calls honey.add internally
```
or better yet, accept it in the initial config:
```
require('honeycomb-beeline')({
    ...MY_CONFIG,
    rootContext: { region, environment }
})
```

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
