### ISSUE TITLE
Add more url data to the span generated by http/https

### ISSUE THREAD

**Issue by numso** [honeycombio/beeline-nodejs#209]
The http/https instrumenters log out the full url:
https://github.com/honeycombio/beeline-nodejs/blob/91b5485b9545f140b6dbb85f5d73a23d85b32d0d/lib/instrumentation/http.js#L48

I propose we add the following data to those spans. I'd be happy to create the PR if this is a desired change.
```
  'url.path': formatOptions.path,
  'url.pathname': formatOptions.pathname,
  'url.search': formatOptions.search,
```

#### Reasoning

I have a case where many of my request urls include a tenant id/name in the baseURL. This makes it difficult to group by url. For example: I would like http://foo.example.com/resource and http://bar.example.com/resource to be grouped together.

It would also make the trace waterfall UI cleaner. I would like to add `url.path` as a column and see `/resource`. Instead I have to add `url` which often truncates the middle to something like `http://fo...esource`

**Comment by numso** [comment]
It would also be very useful to log the statusCode once the request has finished.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
