### ISSUE TITLE
Incorrect timings when streaming in express

### ISSUE THREAD

**Issue by numso** [honeycombio/beeline-nodejs#214]
If you stream your response from express, honeycomb will measure the time it took from request-started to response-started. In some cases there can be a big difference between response-started and response-finished. That extra time is still seen and felt by end users but it is not reflected in honeycomb's base ui (in heatmaps/etc). This also often causes missing spans as the request span is finished but work is still happening.

In this example the response actually took 230ms but the root span reported 160ms. (I was able to avoid missing spans with some tricky use of startAsyncSpan)
![image](https://user-images.githubusercontent.com/1761757/85798473-c61ba080-b6fa-11ea-879f-60016c373305.png)

It looks like this is happening because you're using [on-headers](https://github.com/jshttp/on-headers) in the express instrumentation. Any chance you'd be open to switching to [on-finished](https://github.com/jshttp/on-finished) instead?
https://github.com/honeycombio/beeline-nodejs/blob/b6732978e986d8e74d95809a5dfdfcf179aeb94d/lib/instrumentation/express.js#L166-L168

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
