### ISSUE TITLE
Handling startAsyncSpan when not in parentContext

### ISSUE THREAD

**Issue by wmonk** [honeycombio/beeline-nodejs#247]
Hi! I've been implementing this beeline against my database wrapper, it's working fine and I can see my database spans being reported to honeycomb dashboard which is awesome. The code looks something like this:

```js
class Database {
    // stuff defined here...

    getItem(key) {
        return beeline.startAsyncSpan({ /* data.. */ }, async span => {
            try {
                const { item, capacity } = await this.conn.get(key);
                span.addContext({ capacity });

                return item
            } catch (e) {
                span.addContext({ error: e });

                return Promise.reject(e);
            }
        });
    }
}
```

This works fine in my API calls, as the root handler invokes `beeline.startTrace`. However, my unit tests have started failing, reporting that `span.addContext` is not a function. Digging into the code present the below. The comment suggests that this is a valid use of `startAsyncSpan` which is good, but the use of `askForIssue` suggests it's not... Two things though:
  1. If there is no parent context, can the fn passed to `startAsyncSpan` be passed a "mock" version of a `Span`? Something that maybe noops `addContext`?
  2. It doesn't seem to be passing back the result of the passed `fn`, you can see the `return` on the line after the invocation.

https://github.com/honeycombio/beeline-nodejs/blob/83ace2d461a99dd26b7d700e6cb113ef600416ee/lib/api/libhoney.js#L167-L172

My bigger question is this: Am I implementing `startAsyncSpan` properly? Right now this is a blocker for us using honeycomb.

Happy to open a PR if you're interested!

**Comment by MikeGoldsmith** [comment]
Hey @wmonk - thanks for raising the issue.

FYI You're not finishing the span correctly (eg `beeline.finishSpan(span)`) in your `startAsyncSpan` fn. I don't believe that is causing the problem above though.

It is required that a trace be active and to help with your tests you you could utilse the [mock api](https://github.com/honeycombio/beeline-nodejs/blob/2d58dfa56d4898de6277e00599926fc71b7e9fb6/lib/api/mock.js). You just need to set "mock" as your transmission when calling `api.configure` - [example](https://github.com/honeycombio/beeline-nodejs/blob/2d58dfa56d4898de6277e00599926fc71b7e9fb6/lib/api/index.test.js#L14).

I'm not a super expert on on NodeJS beeline - @katiebayes @toshok may be able to offer more assistance.

**Comment by wmonk** [comment]
@MikeGoldsmith whoops my bad on trying to pseudocode, we are indeed calling `finishSpan` properly, so that's good!

Whoops I missed the mock api, I can definitely use that in testing which will be useful.

The "forcing" of there being an active trace makes it quite a lot harder to adopt honeycomb, as I can't incrementally instrument my code. If I were to replace this span with an event, would it appear in the trace in honeycomb?

**Comment by MikeGoldsmith** [comment]
No worries, we all make pseudocode typos :smile:

I'm unsure what you mean by replace span with an event. Spans and events are effectively equivalent terms where Honeycomb uses event, while the wider Observability term is span. We are trying to converge onto using the standard terms though.

I understand your concern regarding adoption from an inside-out approach where you're instrumenting DB calls which may originate from a path (eg HTTP handler) that hasn't been instrumented yet so a trace won't have been started yet.

The problem seems to lie in that the default implementation does not allow a trace to be started if one hasn't already started. This is because `startTrace` sets some per-trace data, eg fields, dataset, etc. However, most of that is defaulted if not provided.

Maybe we could offer a configuration option to allow `startSpan`/`startAsyncSpan` to start a trace if one has not yet started, relying on default values.

Again, @toshok @katiebayes @paulosman - what do you think?

**Comment by charsleysa** [comment]
isn't this what `.traceActive()` is for? to check if a trace is active, if so wrap code in `startAsyncSpan` otherwise just call code directly

**Comment by wmonk** [comment]
Closing this now, as we better understand how to use these libs.
