### ISSUE TITLE
instrument jest

### ISSUE THREAD

**Issue by danielberndt** [honeycombio/beeline-nodejs#285]
As jest is one of the more popular testing frameworks, it might be helpful to instrument it to get better insights on which tests are slow and why.

I've tried to set it up myself but I'm struggling to get it to work as initiating the beeline in [`globalSetup`](https://jestjs.io/docs/en/configuration#globalsetup-string) still results in 

> The following modules were required before honeycomb-beeline: pg
> These modules will not be instrumented.  Please ensure honeycomb-beeline is required first.

I'm also not 100% sure how to effectively wrap the `describe` and `it` helpers with spans.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
