### ISSUE TITLE
on http/s, content_length is a string, so we can't >, <, etc in HC

### ISSUE THREAD

**Issue by nicwise** [honeycombio/beeline-nodejs#298]
https://github.com/honeycombio/beeline-nodejs/blob/main/lib/instrumentation/https.js#L77

This comes from the header, so it's a string - and it appears that the HC UI then only allows us to use `=`, `!=` etc, and not the vastly more useful `>`, `<` etc.

Can we put it in as a number?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
