### ISSUE TITLE
express authentication middleware instrumentation

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#31]
Possible middleware targets:

* [passportjs](https://www.npmjs.com/package/passport)
* [express-authentication](https://www.npmjs.com/package/express-authentication)

If we can use this to decorate events with usernames/userids automatically, 💥

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
