### ISSUE TITLE
allow setting request ids from other sources

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#34]
if express is behind a load balancer of some sort, chances are there's a request id header we can grab and use instead of generating our own.

1. aws ALB
2. heroku
3. custom user specified request id

we should also add a `meta.request_id_source` that indicates where we sourced it.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
