### ISSUE TITLE
I'm trying to use it with koajs but nothing happens

### ISSUE THREAD

**Issue by paivaric** [honeycombio/beeline-nodejs#366]
No data is being sent.

So, I tried to start a trace and got the `no context in finishSpan` error bellow:

```
  honeycomb-beeline:event finishing span {"payload":{"trace.trace_id":"b18debd58c07305aaf6e015159860d2b","trace.span_id":"a9d5d66fa109b5d4"},"startTime":1622666085553,"startTimeHR":[98293,345650671]} +0ms
  honeycomb-beeline:event -------------------
  honeycomb-beeline:event     honeycomb-beeline error: no context in finishSpan.
  honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:event     out any application stack frames if you'd rather not share those
  honeycomb-beeline:event     Error
  honeycomb-beeline:event     at LibhoneyEventAPI.askForIssue (/Users/paiva/dev/econdos/econdos-backend/node_modules/honeycomb-beeline/lib/api/libhoney.js:344:7)
  honeycomb-beeline:event     at LibhoneyEventAPI.finishSpan (/Users/paiva/dev/econdos/econdos-backend/node_modules/honeycomb-beeline/lib/api/libhoney.js:205:12)
  honeycomb-beeline:event     at LibhoneyEventAPI.finishTrace (/Users/paiva/dev/econdos/econdos-backend/node_modules/honeycomb-beeline/lib/api/libhoney.js:120:10)
  honeycomb-beeline:event     at Function.finishTrace (/Users/paiva/dev/econdos/econdos-backend/node_modules/honeycomb-beeline/lib/api/index.js:101:20)
  honeycomb-beeline:event     at /Users/paiva/dev/econdos/econdos-backend/middleware/honeycomb.js:10:15
  honeycomb-beeline:event     
  honeycomb-beeline:event     ------------------- +0ms```

**Comment by vreynolds** [comment]
Hey @paivaric! As you probably guessed, `koajs` is not instrumented automatically. You were on the right track in starting the trace manually. The error you saw indicates that the trace was finished outside the context in which it started (for example, if it started in an async operation, and finished in another async operation). It's hard to speculate to the specifics without knowing much about your setup.

That being said, I'm curious if you might be better served by [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-js), since it has [koajs instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-koa). That's an alternative to beelines, which you can use to send data to Honeycomb. We have some [docs](https://docs.honeycomb.io/getting-data-in/javascript/opentelemetry/) around how to connect it to Honeycomb.

**Comment by MikeGoldsmith** [comment]
Closing this for now as Beeline doesn't support KoaJS right now, and OpenTelemetry NodeJS SDK does. Feel free to re-open if it’s still relevant.
