### ISSUE TITLE
ampqlib instrumentation

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#39]
This might end up being our first top-level instrumentation that is not a web framework.  It's useful in both modes, though (pushing things onto the queue vs pulling them off.)

**Comment by BrianChristie** [comment]
We use both AMQP (RabbitMQ) and SQS, so +1, this would be useful!

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
