### ISSUE TITLE
Update 3.1.0->3.2.0 breaks express instrumentation

### ISSUE THREAD

**Issue by jugglingthebits** [honeycombio/beeline-nodejs#531]
**Versions**
Node: 16.3.1
Beeline: 3.2.0

**Steps to reproduce**
1. Instrument express app with 3.1.0 successfully
2. Update to 3.2.0 or 3.2.1
3. Traces start having a missing parent span

**Additional context**
The "request" span now has a `trace.parent_id` set, which refers to a nonexistent span.
![grafik](https://user-images.githubusercontent.com/3235163/148449749-ad82b32b-b0cc-40b0-96ac-aed22d332198.png)

**Comment by MikeGoldsmith** [comment]
Thanks for raising @jugglingthebits - We'll look into what's causing this.

**Comment by vreynolds** [comment]
Hey @jugglingthebits, looking at the changeset between those versions, I suspect it has to do with the beeline now automatically detecting both honeycomb and [w3c](https://w3c.github.io/trace-context/#traceparent-header) trace propagation headers since #514 

Is it possible that an upstream service or a load balancer in front of your application is starting a distributed trace, but is not configured to send data to Honeycomb?

If this is what's going on, and you don't want the beeline to parse the incoming w3c header, you should be able to explicitly tell the beeline to only use the honeycomb format:

```js
beeline({
    writeKey: "YOUR_API_KEY",
    dataset: "my-dataset-name",
    httpTraceParserHook: beeline.honeycomb.httpTraceParserHook,
});
```

**Comment by jugglingthebits** [comment]
This makes sense: The app in fact runs in Google Cloud Run, which supports tracing and may send the `traceparent` header through it's load balancer (although I can't tell 100% yet as I don't see that documented anywhere).

However, the workaround above isn't working for me - traces are still missing the parent span when I try it.

**Comment by jugglingthebits** [comment]
I didn't know that beeline add this column - it seems to confirm that the missing span comes from Cloud Run tracing support 
![grafik](https://user-images.githubusercontent.com/3235163/148917575-c6cbbfdd-8dc1-465b-bec0-0d8a52306121.png)

**Comment by jugglingthebits** [comment]
This issue may be less of a problem with beeline (although IMO this was a breaking change), but happens also with OTEL instrumentation within GCP. Others have run into this as well https://stackoverflow.com/questions/68245816/google-cloudrun-auto-tracing-causing-missing-spans
Maybe the proper solution would be to have GCP not set tracing headers tracing by default in Cloud Run (and probably other services), but as far as I'm aware, that's not an available option currently.

**Comment by vreynolds** [comment]
Thanks for the context! Yes, in hindsight we probably ought to have made that a major release.

Will dig into the parser hook not working, that's definitely a bug.

**Comment by vreynolds** [comment]
Found the issue with overriding default parsing behavior -- the fix will be coming down the pipes soon!
