### ISSUE TITLE
AWS SQS Instrumentation

### ISSUE THREAD

**Issue by BrianChristie** [honeycombio/beeline-nodejs#67]
I see the readme says to add issues for desired instrumentations, so I'm filing this :).

We use Amazon's SQS extensively in our systems (occasionally together with SNS), it'd be great if the beeline had instrumentation. Any info that would be helpful around this for eventual implementation?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
