### ISSUE TITLE
Push trace creation from express to http/https

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#70]
There's no reason we couldn't create the traces in the http/http instrumentations.  That would let other http frameworks possibly gain the ability to trace, even if we don't handle the framework itself.

I say "possibly" because there's no telling if the async context will get propagated everywhere it needs to be.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
