### ISSUE TITLE
Automatically send memory usage and uptime

### ISSUE THREAD

**Issue by BrianChristie** [honeycombio/beeline-nodejs#72]
Would it make sense for this instrumentation to automatically send memory usage and uptime?

There's [an example in libhoney-js](https://github.com/honeycombio/libhoney-js/blob/master/examples/express-dynamic-fields/express-honey.js#L32:L36) of sending memory in use. It sends ` rss_before, heapTotal_before, heapUsed_before`

The golang-gatekeeper [sends `meta.memory_inuse`](https://github.com/honeycombio/examples/blob/master/golang-gatekeeper/helpers.go#L34)

Also in the [golang-gatekeeper](https://github.com/honeycombio/examples/tree/master/golang-gatekeeper) sample uptime is sent as `meta.process_uptime_sec`

**Comment by kevinmarks** [comment]
Especially now billing is by event and not by size, adding more context by default would be great.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
