### ISSUE TITLE
Field Consistency across Beelines

### ISSUE THREAD

**Issue by BrianChristie** [honeycombio/beeline-nodejs#73]
In #72 (_Automatically send memory usage and uptime_) there's a few fields mentioned that might make sense to add to the beeline-nodejs.

I can see adding suggested fields could become difficult as there are a growing number of beelines.

Perhaps it would make sense to have a beeline-specs repo that can be a reference of fields that are shared between beelines? 

I suggest this as it's what OpenCensus have done: https://github.com/census-instrumentation/opencensus-specs and they have a similar challenge, writing instrumentation libraries and exporters in many languages, attempting to all conform to the same spec.

Our planned use of Honeycomb appears to be storing everything in a single dataset, as this is currently required to use cross-service tracing. Thus we'd want to make sure to be consistent in our field names.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
