### ISSUE TITLE
Koa Support

### ISSUE THREAD

**Issue by kpruden** [honeycombio/beeline-nodejs#74]
Our nodejs stack uses [koa](https://koajs.com/) rather than express, so we don't benefit from the automagic instrumentation of the request pipeline..

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
