### ISSUE TITLE
Apollo Server support

### ISSUE THREAD

**Issue by kpruden** [honeycombio/beeline-nodejs#75]
Our main app server is a GraphQL service using apollo. It would be super awesome if the node beeline was GQL aware and could pull out events and attributes like resolver paths, resolver execution times, etc. Apollo-server includes some built-in tracing support, which it exposes via the `extensions` section in GQL response. I'm not sure if that would be helpful or not..

**Comment by allyjweir** [comment]
Working on an implementation of this, writing a `GraphQLExtension` that can be used with Apollo Engine. Will hopefully post a PR next week with the implementation. Couple of changes to the API of the beeline library required as well as the extension itself that will no doubt raise some discussion.

**Comment by bautistaaa** [comment]
any update here?

**Comment by spire-allyjweir** [comment]
I wrote an almost fully working implementation of this but the blocker is down to the way that Apollo works with nested entities. There isn't enough data or hooks in the query resolver to properly trace the nested entities. For example:

```
{ 
    author: {
        id: 123,
        name: 'Dave'
    },
    posts: [
        {
            id: 1,
            title: 'foobar'
        },
        {
            id: 2,
            title: 'baz'
        }
    ]
}
```

With this response we could query but the trace would show the `id` and `title` for all the posts at the same depth rather than being grouped by item in the array.

There is more discussion in the Honeycomb Pollinators slack channel here: https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1563552169373400

So, at least personally, I am not working on an integration for this. Others in the community might still be working on it.

**Comment by allyjweir** [comment]
I wrote an almost fully working implementation of this but the blocker is down to the way that Apollo works with nested entities. There isn't enough data or hooks in the query resolver to properly trace the nested entities. For example:

```
{ 
    author: {
        id: 123,
        name: 'Dave'
    },
    posts: [
        {
            id: 1,
            title: 'foobar'
        },
        {
            id: 2,
            title: 'baz'
        }
    ]
}
```

With this response we could query but the trace would show the `id` and `title` for all the posts at the same depth rather than being grouped by item in the array.

There is more discussion in the Honeycomb Pollinators slack channel here: https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1563552169373400

So, at least personally, I am not working on an integration for this. Others in the community might still be working on it.

**Comment by bautistaaa** [comment]
@kpruden Are you able to use Apollo Links to start traces/create spans. I am trying to go that route with no success. Not sure if you or @allyjweir have any examples I can look at as far as trying to get some sort of tracing in Apollo Server. Otherwise I may nede to go the Apollo Graph Manager route which I'd like to avoid.

Thanks in advance!

**Comment by allyjweir** [comment]
I might have a code snippet of the implementation I did. Have set a
reminder to send tomorrow AM.

**Comment by bautistaaa** [comment]
Thanks!

Currently trying to use RestDataSource as well. If I have any breakthroughs I'll share them here

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
