### ISSUE TITLE
Add guide for using the API from applications

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#78]
API.md is more reference than guide (even with the examples.)

There's probably room for a guide showing _just_ the parts of the API that are likely to be useful for app developers (i.e. missing things like `addContext`), and with more "you should do it this way" than "here's a selection of artisanally crafted API for your consideration."

Also either more fleshed out examples or a link to one or more repos with example apps.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
