### ISSUE TITLE
[mongodb] add listIndexes instrumentation

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#79]
the mongodb instrumentation now supports wrapping methods that don't take callbacks, and also supports methods that return promises.  should be pretty easy to add `listIndexes` support now.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
