### ISSUE TITLE
[mongodb] tests

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#80]
There are two good pieces here:

1. writing jest tests against an internal (in-memory db) as a minimal smoke test
2. validating the instrumentation against the mongodb test suite.

# jest tests
Probably pretty easy - mongodb-memory-server is looks easy to deal with.  right now we aren't running babel so dealing with all the promises might be a PITA, but shouldn't be too too bad.

# mongodb test suite
This is likely a lot of work.  Unclear how to set things up, but it'd be lovely to run whatever test suite mongodb has after our instrumentation has been applied (both with an active trace and without) on travis-ci.

Testing against multiple versions of the mongodb package would be 🔥 but I imagine a tremendous increase in complexity/test time.

**Comment by toshok** [comment]
overly boilerplate mongodb-plus-jest [here](https://jestjs.io/docs/en/mongodb), but I think we can take what we need from there without wholesale c&p.

**Comment by djanowski** [comment]
https://github.com/honeycombio/beeline-nodejs/pull/393

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
